//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string All_Body {
            get {
                return ResourceManager.GetString("All_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string All_Close {
            get {
                return ResourceManager.GetString("All_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string All_Closed {
            get {
                return ResourceManager.GetString("All_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylinders.
        /// </summary>
        internal static string All_Cylinders {
            get {
                return ResourceManager.GetString("All_Cylinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string All_Details {
            get {
                return ResourceManager.GetString("All_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        internal static string All_Drive {
            get {
                return ResourceManager.GetString("All_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string All_Found {
            get {
                return ResourceManager.GetString("All_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string All_From {
            get {
                return ResourceManager.GetString("All_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string All_Fuel {
            get {
                return ResourceManager.GetString("All_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get pre-approved instantly.
        /// </summary>
        internal static string All_InstantPreapproved {
            get {
                return ResourceManager.GetString("All_InstantPreapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string All_Location {
            get {
                return ResourceManager.GetString("All_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes.
        /// </summary>
        internal static string All_Makes {
            get {
                return ResourceManager.GetString("All_Makes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX My Trade/Sell Offers.
        /// </summary>
        internal static string All_MaxAllowance {
            get {
                return ResourceManager.GetString("All_MaxAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        internal static string All_Mileage {
            get {
                return ResourceManager.GetString("All_Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string All_Miles {
            get {
                return ResourceManager.GetString("All_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string All_Models {
            get {
                return ResourceManager.GetString("All_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now open.
        /// </summary>
        internal static string All_NowOpen {
            get {
                return ResourceManager.GetString("All_NowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        internal static string All_Photos {
            get {
                return ResourceManager.GetString("All_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string All_Price {
            get {
                return ResourceManager.GetString("All_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price range.
        /// </summary>
        internal static string All_PriceRange {
            get {
                return ResourceManager.GetString("All_PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string All_Search {
            get {
                return ResourceManager.GetString("All_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search within results....
        /// </summary>
        internal static string All_SearchInResults {
            get {
                return ResourceManager.GetString("All_SearchInResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inventory.
        /// </summary>
        internal static string All_SearchInventory {
            get {
                return ResourceManager.GetString("All_SearchInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transm.
        /// </summary>
        internal static string All_Transm {
            get {
                return ResourceManager.GetString("All_Transm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string All_Type {
            get {
                return ResourceManager.GetString("All_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle(s).
        /// </summary>
        internal static string All_Vehicles {
            get {
                return ResourceManager.GetString("All_Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may also like.
        /// </summary>
        internal static string All_YouMayLike {
            get {
                return ResourceManager.GetString("All_YouMayLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your filters.
        /// </summary>
        internal static string Filter_ChooseYourFilters {
            get {
                return ResourceManager.GetString("Filter_ChooseYourFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than.
        /// </summary>
        internal static string Filter_MoreThan {
            get {
                return ResourceManager.GetString("Filter_MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by : .
        /// </summary>
        internal static string Filter_SortBy {
            get {
                return ResourceManager.GetString("Filter_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        internal static string Filter_Under {
            get {
                return ResourceManager.GetString("Filter_Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string Nav_AboutUs {
            get {
                return ResourceManager.GetString("Nav_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Nav_Admin {
            get {
                return ResourceManager.GetString("Nav_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Nav_All {
            get {
                return ResourceManager.GetString("Nav_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Nav_Blog {
            get {
                return ResourceManager.GetString("Nav_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Nav_Contact {
            get {
                return ResourceManager.GetString("Nav_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Nav_ContactUs {
            get {
                return ResourceManager.GetString("Nav_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertibles.
        /// </summary>
        internal static string Nav_Convertibles {
            get {
                return ResourceManager.GetString("Nav_Convertibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupes.
        /// </summary>
        internal static string Nav_Coupes {
            get {
                return ResourceManager.GetString("Nav_Coupes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit application.
        /// </summary>
        internal static string Nav_GetPrequalified {
            get {
                return ResourceManager.GetString("Nav_GetPrequalified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchbacks.
        /// </summary>
        internal static string Nav_Hatchbacks {
            get {
                return ResourceManager.GetString("Nav_Hatchbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Nav_Inventory {
            get {
                return ResourceManager.GetString("Nav_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Nav_Login {
            get {
                return ResourceManager.GetString("Nav_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our staff.
        /// </summary>
        internal static string Nav_OurStaff {
            get {
                return ResourceManager.GetString("Nav_OurStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule test drive.
        /// </summary>
        internal static string Nav_ScheduleTestDrive {
            get {
                return ResourceManager.GetString("Nav_ScheduleTestDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search inventory.
        /// </summary>
        internal static string Nav_SearchInventory {
            get {
                return ResourceManager.GetString("Nav_SearchInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedans.
        /// </summary>
        internal static string Nav_Sedans {
            get {
                return ResourceManager.GetString("Nav_Sedans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUVs.
        /// </summary>
        internal static string Nav_SUVs {
            get {
                return ResourceManager.GetString("Nav_SUVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        internal static string Nav_Testimonials {
            get {
                return ResourceManager.GetString("Nav_Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucks.
        /// </summary>
        internal static string Nav_Trucks {
            get {
                return ResourceManager.GetString("Nav_Trucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vans.
        /// </summary>
        internal static string Nav_Vans {
            get {
                return ResourceManager.GetString("Nav_Vans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagons.
        /// </summary>
        internal static string Nav_Wagons {
            get {
                return ResourceManager.GetString("Nav_Wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string Title_AboutUs {
            get {
                return ResourceManager.GetString("Title_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vehicle(s).
        /// </summary>
        internal static string Title_AllVehicles {
            get {
                return ResourceManager.GetString("Title_AllVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Title_Blog {
            get {
                return ResourceManager.GetString("Title_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Title_Category {
            get {
                return ResourceManager.GetString("Title_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Title_ContactUs {
            get {
                return ResourceManager.GetString("Title_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Title_Employees {
            get {
                return ResourceManager.GetString("Title_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get prequalified.
        /// </summary>
        internal static string Title_GetPrequalified {
            get {
                return ResourceManager.GetString("Title_GetPrequalified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our staff.
        /// </summary>
        internal static string Title_OutStaff {
            get {
                return ResourceManager.GetString("Title_OutStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string Title_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Title_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        internal static string Title_Terms {
            get {
                return ResourceManager.GetString("Title_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} vehicle(s).
        /// </summary>
        internal static string Title_TotalVehicles {
            get {
                return ResourceManager.GetString("Title_TotalVehicles", resourceCulture);
            }
        }
    }
}
